### ISSUE TITLE
Issue parsing xml containing CDATA tags

### ISSUE THREAD

**Issue by petemcfarlane** [hobnob/xmlStreamReader#18]
I'm having problems parsing XML with nodes already containing CDATA tags. I have managed to write a test to demonstrate my failing scenario, but haven't been able to fix it yet. 

The failing test looks like 
```
    public function testParsesStringAlreadyContainingCdataTags()
    {
        $passed    = FALSE;
        $xmlParser = new Parser();

        $callback = function() use (&$passed) {
            $passed = TRUE;
        };

        $xmlParser->registerCallback('/General/Country', $callback);
        $xmlParser->parse("<General><Country><![CDATA[Bulgaria ]]></Country></General>");

        $this->assertTrue( $passed );
    }
```

which creates this error
```
Exception: String could not be parsed as XML

~/xmlStreamReader/classes/Hobnob/XmlStreamReader/Parser.php:379
~/xmlStreamReader/classes/Hobnob/XmlStreamReader/Parser.php:326
~/xmlStreamReader/classes/Hobnob/XmlStreamReader/Parser.php:206
~/xmlStreamReader/classes/Hobnob/XmlStreamReader/Parser.php:94
~/xmlStreamReader/tests/ParserTest.php:363

```

I'm pretty sure it's something to do with the method `addCdata()` because if I comment that out then this test passes, but breaks others in the suite.

If you have any suggestions on how to fix this I'd be happy to try and submit a PR?

**Comment by petemcfarlane** [comment]
I think this may have been to do with my php version, as I have upgraded and it now works fine!

Details of the version **not** working:
```
PHP 5.6.10 (cli) (built: Jul  6 2015 14:28:54) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.2.7, Copyright (c) 2002-2015, by Derick Retinas
```
Details of working version:
```
PHP 5.6.17 (cli) (built: Jan  8 2016 10:27:48) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
```

**Comment by hobnob** [comment]
Hi @petemcfarlane ,

Thanks for taking the time to report back. I wonder what changed between these versions? I'll see if I can add that specific version to Travis to re-create what you saw. When that'll be I don't really know, but I'll be sure to update when I do

Cheers
David
